name: 'Get Package Semver'
description: 'Give current and next package version based on our internal process'
author: 'Luos'
inputs:
  type:
    description: 'Type of package update. Example: major, minor, patch, rc'
    required: false
outputs:
  version:
    description: 'The new version of the package'
runs:
  using: 'node12'
  main: './dist/index.js'
